"""
Chore Dashboard API
FastAPI backend connecting React frontend to SQLite database.

Run with: uvicorn main:app --reload --port 8000
API docs: http://localhost:8000/docs (auto-generated by FastAPI)
"""

from fastapi import FastAPI, HTTPException, Query, Path
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import Optional, Literal
from datetime import date, datetime
from contextlib import contextmanager
import sqlite3
import uuid
import os

# =============================================================================
# CONFIG
# =============================================================================

DATABASE_PATH = os.environ.get("CHORE_DB_PATH", "chores.db")

app = FastAPI(
    title="Chore Dashboard API",
    description="API for managing household chores with scheduling and completion tracking",
    version="1.0.0"
)

# CORS - allow React dev server to call API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://localhost:5173", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# =============================================================================
# DATABASE HELPERS
# =============================================================================

def dict_factory(cursor, row):
    """Convert sqlite3 rows to dictionaries."""
    fields = [column[0] for column in cursor.description]
    return {key: value for key, value in zip(fields, row)}


@contextmanager
def get_db():
    """Database connection context manager."""
    conn = sqlite3.connect(DATABASE_PATH)
    conn.row_factory = dict_factory
    conn.execute("PRAGMA foreign_keys = ON")
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def generate_id() -> str:
    """Generate a UUID for new records (matches frontend's crypto.randomUUID())."""
    return str(uuid.uuid4())


# =============================================================================
# PYDANTIC MODELS (Request/Response schemas)
# =============================================================================

FrequencyType = Literal["daily", "weekly", "monthly", "quarterly", "adhoc"]
TimeOfDayType = Literal["AM", "PM"]


class ChoreBase(BaseModel):
    """Base chore fields for create/update."""
    name: str = Field(..., min_length=1, max_length=200)
    frequency: FrequencyType
    time_of_day: TimeOfDayType = "AM"
    minutes: int = Field(default=10, gt=0, le=480)
    day_of_week: Optional[int] = Field(default=None, ge=0, le=6)
    week_of_month: Optional[int] = Field(default=None, ge=1, le=4)
    month_of_quarter: Optional[int] = Field(default=None, ge=1, le=3)
    scheduled_date: Optional[date] = None


class ChoreCreate(ChoreBase):
    """Schema for creating a new chore."""
    pass


class ChoreUpdate(BaseModel):
    """Schema for updating a chore (all fields optional)."""
    name: Optional[str] = Field(default=None, min_length=1, max_length=200)
    frequency: Optional[FrequencyType] = None
    time_of_day: Optional[TimeOfDayType] = None
    minutes: Optional[int] = Field(default=None, gt=0, le=480)
    day_of_week: Optional[int] = Field(default=None, ge=0, le=6)
    week_of_month: Optional[int] = Field(default=None, ge=1, le=4)
    month_of_quarter: Optional[int] = Field(default=None, ge=1, le=3)
    scheduled_date: Optional[date] = None


class ChoreResponse(ChoreBase):
    """Schema for chore responses."""
    id: str
    created_at: str
    updated_at: str
    
    class Config:
        from_attributes = True


class CompletionCreate(BaseModel):
    """Schema for marking a chore complete."""
    chore_id: str
    completed_date: date


class CompletionResponse(BaseModel):
    """Schema for completion responses."""
    chore_id: str
    completed_date: date
    completed_at: str


class DateChoresResponse(BaseModel):
    """Schema for chores on a specific date with completion status."""
    date: date
    chores: list[dict]
    summary: dict


class BulkCompletionStatus(BaseModel):
    """Schema for getting completion status for multiple chores."""
    date: date
    completions: dict[str, bool]  # chore_id -> is_completed


# =============================================================================
# ENDPOINTS: Chores CRUD
# =============================================================================

@app.get("/chores", response_model=list[ChoreResponse], tags=["Chores"])
def list_chores(
    frequency: Optional[FrequencyType] = Query(default=None, description="Filter by frequency"),
    time_of_day: Optional[TimeOfDayType] = Query(default=None, description="Filter by AM/PM"),
    search: Optional[str] = Query(default=None, description="Search chore names")
):
    """
    List all active chores with optional filters.
    Used by the Manage tab in the frontend.
    """
    with get_db() as conn:
        query = """
            SELECT id, name, frequency, time_of_day, minutes,
                   day_of_week, week_of_month, month_of_quarter, 
                   scheduled_date, created_at, updated_at
            FROM chores
            WHERE is_active = 1
        """
        params = []
        
        if frequency:
            query += " AND frequency = ?"
            params.append(frequency)
        
        if time_of_day:
            query += " AND time_of_day = ?"
            params.append(time_of_day)
        
        if search:
            query += " AND name LIKE ?"
            params.append(f"%{search}%")
        
        query += """
            ORDER BY 
                (SELECT sort_order FROM frequencies WHERE id = frequency),
                time_of_day,
                name
        """
        
        return conn.execute(query, params).fetchall()


@app.get("/chores/{chore_id}", response_model=ChoreResponse, tags=["Chores"])
def get_chore(chore_id: str):
    """Get a single chore by ID."""
    with get_db() as conn:
        chore = conn.execute(
            """SELECT id, name, frequency, time_of_day, minutes,
                      day_of_week, week_of_month, month_of_quarter,
                      scheduled_date, created_at, updated_at
               FROM chores WHERE id = ? AND is_active = 1""",
            (chore_id,)
        ).fetchone()
        
        if not chore:
            raise HTTPException(status_code=404, detail="Chore not found")
        
        return chore


@app.post("/chores", response_model=ChoreResponse, status_code=201, tags=["Chores"])
def create_chore(chore: ChoreCreate):
    """
    Create a new chore.
    Validates that scheduling fields match the frequency type.
    """
    # Validate scheduling fields based on frequency
    _validate_scheduling_fields(chore)
    
    chore_id = generate_id()
    now = datetime.now().isoformat()
    
    with get_db() as conn:
        conn.execute(
            """INSERT INTO chores 
               (id, name, frequency, time_of_day, minutes, 
                day_of_week, week_of_month, month_of_quarter, 
                scheduled_date, created_at, updated_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                chore_id,
                chore.name,
                chore.frequency,
                chore.time_of_day,
                chore.minutes,
                chore.day_of_week,
                chore.week_of_month,
                chore.month_of_quarter,
                chore.scheduled_date.isoformat() if chore.scheduled_date else None,
                now,
                now
            )
        )
        
        return {
            "id": chore_id,
            **chore.model_dump(),
            "scheduled_date": chore.scheduled_date.isoformat() if chore.scheduled_date else None,
            "created_at": now,
            "updated_at": now
        }


@app.put("/chores/{chore_id}", response_model=ChoreResponse, tags=["Chores"])
def update_chore(chore_id: str, chore: ChoreUpdate):
    """
    Update an existing chore.
    Only provided fields are updated (PATCH-like behavior).
    """
    with get_db() as conn:
        # Get existing chore
        existing = conn.execute(
            "SELECT * FROM chores WHERE id = ? AND is_active = 1",
            (chore_id,)
        ).fetchone()
        
        if not existing:
            raise HTTPException(status_code=404, detail="Chore not found")
        
        # Merge updates with existing data
        update_data = chore.model_dump(exclude_unset=True)
        
        if not update_data:
            raise HTTPException(status_code=400, detail="No fields to update")
        
        # Build dynamic UPDATE query
        set_clauses = []
        params = []
        for field, value in update_data.items():
            set_clauses.append(f"{field} = ?")
            if field == "scheduled_date" and value:
                params.append(value.isoformat())
            else:
                params.append(value)
        
        params.append(chore_id)
        
        conn.execute(
            f"UPDATE chores SET {', '.join(set_clauses)} WHERE id = ?",
            params
        )
        
        # Return updated chore
        return conn.execute(
            """SELECT id, name, frequency, time_of_day, minutes,
                      day_of_week, week_of_month, month_of_quarter,
                      scheduled_date, created_at, updated_at
               FROM chores WHERE id = ?""",
            (chore_id,)
        ).fetchone()


@app.delete("/chores/{chore_id}", status_code=204, tags=["Chores"])
def delete_chore(chore_id: str):
    """
    Soft delete a chore (sets is_active = 0).
    Preserves completion history.
    """
    with get_db() as conn:
        result = conn.execute(
            "UPDATE chores SET is_active = 0 WHERE id = ? AND is_active = 1",
            (chore_id,)
        )
        
        if result.rowcount == 0:
            raise HTTPException(status_code=404, detail="Chore not found")


# =============================================================================
# ENDPOINTS: Date-based queries (Calendar view)
# =============================================================================

@app.get("/chores/date/{target_date}", response_model=DateChoresResponse, tags=["Calendar"])
def get_chores_for_date(target_date: date):
    """
    Get all chores scheduled for a specific date.
    This powers the calendar day view - returns chores grouped by AM/PM
    with their completion status.
    """
    # Calculate scheduling values for the date
    # Note: Python weekday() is 0=Mon, but JS/our schema uses 0=Sun
    day_of_week = (target_date.weekday() + 1) % 7
    week_of_month = (target_date.day - 1) // 7 + 1
    month_of_quarter = (target_date.month - 1) % 3 + 1
    date_str = target_date.isoformat()
    
    with get_db() as conn:
        # Get chores for this date
        chores = conn.execute(
            """
            SELECT 
                c.id,
                c.name, 
                c.frequency,
                c.time_of_day,
                c.minutes,
                CASE WHEN ct.chore_id IS NOT NULL THEN 1 ELSE 0 END as is_completed
            FROM chores c
            LEFT JOIN completed_tasks ct 
                ON c.id = ct.chore_id AND ct.completed_date = ?
            WHERE c.is_active = 1
              AND (
                c.frequency = 'daily'
                OR (c.frequency = 'weekly' AND c.day_of_week = ?)
                OR (c.frequency = 'monthly' AND c.week_of_month = ? AND c.day_of_week = ?)
                OR (c.frequency = 'quarterly' AND c.month_of_quarter = ? AND c.week_of_month = ? AND c.day_of_week = ?)
                OR (c.frequency = 'adhoc' AND c.scheduled_date = ?)
              )
            ORDER BY c.time_of_day, c.name
            """,
            (date_str, day_of_week, week_of_month, day_of_week,
             month_of_quarter, week_of_month, day_of_week, date_str)
        ).fetchall()
        
        # Calculate summary
        total_count = len(chores)
        completed_count = sum(1 for c in chores if c["is_completed"])
        total_minutes = sum(c["minutes"] for c in chores)
        completed_minutes = sum(c["minutes"] for c in chores if c["is_completed"])
        
        # Convert is_completed to boolean for JSON
        for chore in chores:
            chore["is_completed"] = bool(chore["is_completed"])
        
        return {
            "date": target_date,
            "chores": chores,
            "summary": {
                "total_count": total_count,
                "completed_count": completed_count,
                "remaining_count": total_count - completed_count,
                "total_minutes": total_minutes,
                "completed_minutes": completed_minutes,
                "remaining_minutes": total_minutes - completed_minutes,
                "progress_percent": round((completed_count / total_count) * 100) if total_count > 0 else 0
            }
        }


@app.get("/calendar/month/{year}/{month}", tags=["Calendar"])
def get_month_summary(year: int, month: int = Path(..., ge=1, le=12)):
    """
    Get summary data for an entire month (for calendar heatmap).
    Returns count and minutes for each day.
    """
    from calendar import monthrange
    
    _, days_in_month = monthrange(year, month)
    
    results = {}
    for day in range(1, days_in_month + 1):
        target_date = date(year, month, day)
        day_data = get_chores_for_date(target_date)
        results[target_date.isoformat()] = day_data["summary"]
    
    return results


# =============================================================================
# ENDPOINTS: Completions
# =============================================================================

@app.post("/completions", response_model=CompletionResponse, status_code=201, tags=["Completions"])
def mark_complete(completion: CompletionCreate):
    """Mark a chore as complete for a specific date."""
    with get_db() as conn:
        # Verify chore exists
        chore = conn.execute(
            "SELECT id FROM chores WHERE id = ? AND is_active = 1",
            (completion.chore_id,)
        ).fetchone()
        
        if not chore:
            raise HTTPException(status_code=404, detail="Chore not found")
        
        try:
            now = datetime.now().isoformat()
            conn.execute(
                """INSERT INTO completed_tasks (chore_id, completed_date, completed_at)
                   VALUES (?, ?, ?)""",
                (completion.chore_id, completion.completed_date.isoformat(), now)
            )
            
            return {
                "chore_id": completion.chore_id,
                "completed_date": completion.completed_date,
                "completed_at": now
            }
        except sqlite3.IntegrityError:
            raise HTTPException(
                status_code=409, 
                detail="Chore already marked complete for this date"
            )


@app.delete("/completions/{chore_id}/{completed_date}", status_code=204, tags=["Completions"])
def unmark_complete(chore_id: str, completed_date: date):
    """Remove completion status for a chore on a specific date."""
    with get_db() as conn:
        result = conn.execute(
            "DELETE FROM completed_tasks WHERE chore_id = ? AND completed_date = ?",
            (chore_id, completed_date.isoformat())
        )
        
        if result.rowcount == 0:
            raise HTTPException(status_code=404, detail="Completion record not found")


@app.post("/completions/toggle", tags=["Completions"])
def toggle_completion(completion: CompletionCreate):
    """
    Toggle completion status (convenience endpoint for the frontend).
    Returns the new state.
    """
    with get_db() as conn:
        # Check if already completed
        existing = conn.execute(
            "SELECT 1 FROM completed_tasks WHERE chore_id = ? AND completed_date = ?",
            (completion.chore_id, completion.completed_date.isoformat())
        ).fetchone()
        
        if existing:
            # Remove completion
            conn.execute(
                "DELETE FROM completed_tasks WHERE chore_id = ? AND completed_date = ?",
                (completion.chore_id, completion.completed_date.isoformat())
            )
            return {"chore_id": completion.chore_id, "is_completed": False}
        else:
            # Add completion
            now = datetime.now().isoformat()
            conn.execute(
                """INSERT INTO completed_tasks (chore_id, completed_date, completed_at)
                   VALUES (?, ?, ?)""",
                (completion.chore_id, completion.completed_date.isoformat(), now)
            )
            return {"chore_id": completion.chore_id, "is_completed": True}


@app.get("/completions/{target_date}", response_model=BulkCompletionStatus, tags=["Completions"])
def get_completions_for_date(target_date: date):
    """Get completion status for all chores on a specific date."""
    with get_db() as conn:
        completions = conn.execute(
            "SELECT chore_id FROM completed_tasks WHERE completed_date = ?",
            (target_date.isoformat(),)
        ).fetchall()
        
        return {
            "date": target_date,
            "completions": {c["chore_id"]: True for c in completions}
        }


# =============================================================================
# ENDPOINTS: Data management (Export/Import/Reset)
# =============================================================================

@app.get("/export", tags=["Data"])
def export_data():
    """Export all chores and completions (matches frontend export format)."""
    with get_db() as conn:
        chores_raw = conn.execute(
            """SELECT id, name, frequency, time_of_day as time, minutes,
                      day_of_week as dayOfWeek, week_of_month as weekOfMonth, 
                      month_of_quarter as monthOfQuarter, scheduled_date as scheduledDate
               FROM chores WHERE is_active = 1"""
        ).fetchall()
        
        # Group by frequency (matching frontend structure)
        chores = {"daily": [], "weekly": [], "monthly": [], "quarterly": [], "adhoc": []}
        for c in chores_raw:
            freq = c.pop("frequency")
            # Remove None values
            chores[freq].append({k: v for k, v in c.items() if v is not None})
        
        completions = conn.execute(
            "SELECT chore_id, completed_date FROM completed_tasks"
        ).fetchall()
        
        # Group completions by date (matching frontend structure)
        completed_tasks = {}
        for c in completions:
            date_key = c["completed_date"]
            if date_key not in completed_tasks:
                completed_tasks[date_key] = {}
            completed_tasks[date_key][c["chore_id"]] = True
        
        return {
            "chores": chores,
            "completedTasks": completed_tasks,
            "exportedAt": int(datetime.now().timestamp() * 1000)
        }


@app.post("/import", tags=["Data"])
def import_data(data: dict):
    """Import chores and completions from exported JSON."""
    with get_db() as conn:
        # Clear existing data
        conn.execute("DELETE FROM completed_tasks")
        conn.execute("DELETE FROM chores")
        
        # Import chores
        chores = data.get("chores", {})
        for frequency, chore_list in chores.items():
            for c in chore_list:
                conn.execute(
                    """INSERT INTO chores 
                       (id, name, frequency, time_of_day, minutes,
                        day_of_week, week_of_month, month_of_quarter, scheduled_date)
                       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                    (
                        c.get("id", generate_id()),
                        c["name"],
                        frequency,
                        c.get("time", "AM"),
                        c.get("minutes", 10),
                        c.get("dayOfWeek"),
                        c.get("weekOfMonth"),
                        c.get("monthOfQuarter"),
                        c.get("scheduledDate")
                    )
                )
        
        # Import completions
        completed_tasks = data.get("completedTasks", {})
        for date_key, completions in completed_tasks.items():
            for chore_id, is_complete in completions.items():
                if is_complete:
                    try:
                        conn.execute(
                            """INSERT INTO completed_tasks (chore_id, completed_date)
                               VALUES (?, ?)""",
                            (chore_id, date_key)
                        )
                    except sqlite3.IntegrityError:
                        pass  # Skip if chore doesn't exist
        
        return {"status": "imported", "message": "Data imported successfully"}


@app.post("/reset", tags=["Data"])
def reset_data():
    """Reset database to initial state with seed data."""
    import subprocess
    
    with get_db() as conn:
        # Clear all data
        conn.execute("DELETE FROM completed_tasks")
        conn.execute("DELETE FROM chores")
    
    # Re-run seed data from schema
    # In production, you'd have a separate seed file
    with get_db() as conn:
        seed_sql = """
        INSERT INTO chores (name, frequency, time_of_day, minutes) VALUES
            ('Make bed', 'daily', 'AM', 3),
            ('Scoop litter boxes', 'daily', 'AM', 5),
            ('Wipe bathroom sink and counter', 'daily', 'AM', 3),
            ('Vacuum all floors', 'daily', 'AM', 20),
            ('Dishes / load dishwasher', 'daily', 'PM', 10),
            ('Wipe kitchen counters', 'daily', 'PM', 5),
            ('Take out trash when full', 'daily', 'PM', 5),
            ('Pick up clutter / return items to place', 'daily', 'PM', 10);

        INSERT INTO chores (name, frequency, time_of_day, minutes, day_of_week) VALUES
            ('Mop hard floors', 'weekly', 'AM', 20, 1),
            ('Clean toilets', 'weekly', 'AM', 10, 2),
            ('Clean showers/tubs', 'weekly', 'AM', 15, 2),
            ('Dust surfaces', 'weekly', 'AM', 15, 3),
            ('Clean mirrors', 'weekly', 'AM', 10, 3),
            ('Wipe down kitchen appliances', 'weekly', 'PM', 10, 4),
            ('Brush dog and cats', 'weekly', 'PM', 20, 4),
            ('Empty all small trash cans', 'weekly', 'AM', 10, 5),
            ('Change bed linens', 'weekly', 'AM', 15, 6),
            ('Laundry (wash, dry, fold, put away)', 'weekly', 'AM', 45, 6),
            ('Wash food and water bowls', 'weekly', 'PM', 10, 0);
        """
        conn.executescript(seed_sql)
    
    return {"status": "reset", "message": "Database reset to initial state"}


# =============================================================================
# HELPERS
# =============================================================================

def _validate_scheduling_fields(chore: ChoreCreate):
    """Validate that scheduling fields are appropriate for the frequency type."""
    freq = chore.frequency
    
    if freq == "daily":
        # Daily chores shouldn't have scheduling fields
        pass
    elif freq == "weekly":
        if chore.day_of_week is None:
            raise HTTPException(
                status_code=400, 
                detail="Weekly chores require day_of_week"
            )
    elif freq == "monthly":
        if chore.day_of_week is None or chore.week_of_month is None:
            raise HTTPException(
                status_code=400,
                detail="Monthly chores require day_of_week and week_of_month"
            )
    elif freq == "quarterly":
        if any(x is None for x in [chore.day_of_week, chore.week_of_month, chore.month_of_quarter]):
            raise HTTPException(
                status_code=400,
                detail="Quarterly chores require day_of_week, week_of_month, and month_of_quarter"
            )
    elif freq == "adhoc":
        if chore.scheduled_date is None:
            raise HTTPException(
                status_code=400,
                detail="Ad-hoc chores require scheduled_date"
            )


# =============================================================================
# STARTUP
# =============================================================================

@app.on_event("startup")
def startup_event():
    """Verify database exists on startup."""
    if not os.path.exists(DATABASE_PATH):
        print(f"WARNING: Database not found at {DATABASE_PATH}")
        print("Run the schema SQL to create it, or set CHORE_DB_PATH environment variable")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
